wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23.dev1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    t:
      4: 3.6.8
      5: 0.10.23.dev1
      8:
      - 5
