[version]
path = "wandb/__init__.py"

[build.hooks.custom]
path = "hatch_build.py"

[build]
include = [
    "wandb/__init__.pyi",
    "wandb/py.typed",
    "package_readme.md",
    "wandb/**/*.py",
    "wandb/**/*.sh",
]
exclude = [
    "wandb/vendor/orjson",
]

[build.targets.sdist]
include = [
    "core",
    "gpu_stats",
    "wandb/vendor/orjson",
    "wandb/py.typed",
    "package_readme.md",
    "wandb/__init__.pyi",
    "wandb/**/*.py",
    "wandb/**/*.sh",
]
exclude = ["tests/"]
