# NOTE: Paths are relative to the root of the repo

[tool.ariadne-codegen]
schema_path = "core/api/graphql/schemas/schema-latest.graphql"
queries_path = "tools/graphql_codegen/automations/"

target_package_path = "wandb/automations"
target_package_name = "_generated"

include_all_inputs = false # Only generate input types needed for queries
include_all_enums = false  # Only generate enums needed for queries

plugins = [
    "ariadne_codegen.contrib.extract_operations.ExtractOperationsPlugin",
    "graphql_codegen.plugin.GraphQLCodegenPlugin",
]

[tool.ariadne-codegen.scalars.ID]
type = "wandb._pydantic.GQLId"

[tool.ariadne-codegen.scalars.JSONString]
type = "str"

[tool.ariadne-codegen.scalars.DateTime]
type = "datetime.datetime"
