[package]
name = "wandb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.2.0"

[build-dependencies]
protobuf-codegen = "3.2.0"
