name: Build Launch Agent

permissions:
  contents: read
  id-token: write # required for OIDC authentication

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false
        description: wandb ref to build agent from
        default: main
      tagName:
        type: string
        required: true
        description: Tag Name for the launch agent

defaults:
  run:
    working-directory: ./tools/launch_release/build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: set-up-gcloud-sdk
        name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - id: set-up-gcp-credentials
        name: Set up GCP credentials
        uses: "google-github-actions/auth@v3"
        with:
          project_id: ${{ secrets.GCP_REGISTRY_PROJECT_NAME }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_REGISTRY_SA }}

      - id: configure-docker-context
        name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - id: build
        name: Build launch agent
        run: |
          docker context create builder
          docker buildx create --use

          REF=${{ github.event.inputs.ref }}

          TAG=${{ github.event.inputs.tagName }}

          echo Building launch agent image for version $TAG
          docker buildx build --platform linux/amd64,linux/arm64 --build-arg REF=$REF -t wandb/launch-agent-dev:$TAG -t wandb/launch-agent-dev:latest . --push
