name: Validate PR title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  cc:
    name: check conventional commit compliance
    runs-on: ubuntu-latest
    steps:
      # check the basic semantic compliance of the PR title
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            docs
            style
            chore
            revert
            security
          # Product based scopes
          scopes: |
            artifacts
            registries
            automations
            integrations
            launch
            sdk
            sweeps
            leet
          requireScope: false
          # Ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
