name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.8"
      - uses: actions/setup-go@v6
        with:
          go-version-file: core/go.mod
          cache-dependency-path: core/go.sum
      - name: setup env
        run: |
          ./core/scripts/code-checks.sh update
      # remove this once we upgrade to Python 3.9+
      - name: install astunparse
        run: pip install astunparse
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage pre-push --all-files
        env:
          SKIP: go-generate-graphql
