name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install maturin
        run: pip install maturin
      - name: Activate python venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Build python package with maturin
        working-directory: ./experimental/client-rust
        run: maturin develop
      # - name: Build rust binary for testing
      #   working-directory: ./experimental/client-rust
      #   run: cargo build --verbose
      # - name: Run tests
      #   working-directory: ./experimental/client-rust
      #   run: cargo test --verbose
