name: Update Linters
on:
  schedule:
    - cron:  '0 10 * * 1'  # Every Monday at 10:00 UTC

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update linter versions
        run: python tools/update_linters.py
      - name: Reformat with black
        run: black .
      - name: Reformat code in docstrings with blacken-docs
        run: blacken-docs $(find wandb tests tools -name '*.py')
      - name: Fix fixable issues with ruff
        run: ruff --fix-only .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Update lint tool versions
            title: |
              style(sdk): automatically update linting tools
            body: |
              Update the lint tools and re-run them to fix any issues

              This automation run the script `tools/update_linters.py` to update tools,
              and then ran:

              ```bash
              black .
              blacken-docs $(find wandb tests tools -name '*.py')
              ruff --fix .
              ```

              Auto-generated by `.github/workflows/update-linters.yml`
            branch: update-dependencies
            labels: |
              - dependencies
              - auto-merge
            reviewers: |
              wandb/sdk-team
              moredatarequired
